# docker-compose.yml

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: twitter_db
      POSTGRES_USER: twitter_user
      POSTGRES_PASSWORD: twitter_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twitter_user -d twitter_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - ./env.dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://twitter_user:twitter_password@db:5432/twitter_db
      - POSTGRES_DB=twitter_db
      - POSTGRES_USER=twitter_user
      - POSTGRES_PASSWORD=twitter_password
      - DB_HOST=db
      - DB_PORT=5432
    restart: unless-stopped

volumes:
  postgres_data: